version: '3.7'
services:
  vpn:
     depends_on:
       - stunnel
  stunnel:
    image: stunnel
    build:
        context: ./dockerfiles-stunnel
    volumes:
      - ./stunnel/stunnel.conf:/etc/stunnel/stunnel.conf
      - ./stunnel/certs/ca.pem:/etc/stunnel/ca.pem
    entrypoint: stunnel
    network_mode: host
    restart: always
